#pragma once

/* Base version of the Vynx.dev Autoloader (VYNX) content.
 * Bump this when the autoloader frontend changes — it triggers the app-cache
 * update and also marks the matching VYNXI installer build. */
#define VYNX_VERSION "2.1"

/* Full build version (stable: <base>, dev: <base>-dev-<hash|timestamp>),
 * generated by tools/gen_version.py — see include/vynxi_version.h */
#include "vynxi_version.h"

/* Network Settings — arbitrary port, chosen to avoid colliding with other
 * homebrew HTTP servers (must match the deeplink in assets/param.json.template) */
#define VYNXI_PORT 18181

/* Title ID of the installed homescreen app ("Vynx.dev Autoloader") */
#define VYNX_TITLE_ID "VYNX00001"

/* Process identity — used to kill stale installer instances on startup */
#define VYNXI_THREAD_NAME "vynxi.elf"

/* Routes */
#define ROUTE_INDEX "/"
#define ROUTE_INDEX_HTML "/index.html"
#define ROUTE_CACHE_MANIFEST "/cache.appcache"
#define ROUTE_INSTALL "/install"
#define ROUTE_VERSION "/version"
#define ROUTE_CLEAR_WEBKIT_DATA "/clear-webkit-data"
#define ROUTE_EXIT "/exit"

/* Logging (implementation in log.c) */
void vynxi_log(const char *fmt, ...);
size_t vynxi_wait_logs(size_t *pos, char *out_buf, size_t max_len);
void vynxi_log_wakeup(void);

/* Notifications (declared in notification.h) */
#include "notification.h"
